import Head from "next/head";
import { useEffect, useState } from "react";
import Banner from "../components/Banner";
import Header from "../components/Header";
import Logo from "../components/logo";
import SurahCard from "../components/SurahCard";
import { getAllSurahs } from "../core/services/surah.service";

export default function Home() {
  const [surahs, setSurahs] = useState([]);
  useEffect(() => {
    getAllSurahs()
      .then((res) => {
        console.log(res);
        setSurahs(res.data.data);
      })
      .catch((err) => console.log(err));
  }, []);
  return (
    <div>
      <Head>
        <title>Al Quran</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <Header />
        <Banner />
        <div className="surahs-wrapper px-[10%] py-10 flex items-center gap-5 flex-wrap">
          {surahs.map((surah) => (
            <SurahCard {...surah} key={surah.englishName} />
          ))}
        </div>
      </div>
    </div>
  );
}
